Models/ErrorViewModel.cs
namespace SessionDI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/PersonViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace SessionDI.Models
{
    public class Person
    {
        private string _fullname;
        private int _age;

        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }

        public int Id { set; get; }
        public string FullNames
        {
            get
            {
                return FullNames = $"{LastName} {FirstName}";
            }
            set
            {
                _fullname = value;
            }
        }

        [Required]
        public string Gender { get; set; }

        public string BirthPlace { get; set; }

        [RegularExpression(@"^([0-9]{9,})$", ErrorMessage = "Wrong mobile"!)]
        public string PhoneNumber { get; set; }

        [Required]
        public DateTime DateOfBirth { get; set; }

        [EmailAddress]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]
        public string Email { get; set; }

        public bool IsGraduated { set; get; }

        public int Age
        {
            set
            {
                _age = value;
            }
            get
            {
                return DateTime.Now.Year - DateOfBirth.Year;
            }
        }

        public int CalculateAgeCorrect(DateTime birthDate, DateTime now)
        {
            int age = now.Year - birthDate.Year;

            if (now.Month < birthDate.Month || (now.Month == birthDate.Month && now.Day < birthDate.Day))
                age--;

            return Age;
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Http;
using SessionDI.Models;

namespace SessionDI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        static List<Person> members = new List<Person>
        {
            new Person{
                FirstName = "Long",
                LastName = "Bao",
                Gender = "Male",
                DateOfBirth = new DateTime(1994,1,16),
                PhoneNumber="",
                BirthPlace = "Bac Ninh",
                IsGraduated  = false,
                Age = 27
            },
            new Person{
                FirstName = "Dat",
                LastName = "Dam Tuan",
                Gender = "Male",
                DateOfBirth = new DateTime(1996,7,14),
                PhoneNumber="",
                BirthPlace = "Ha noi",
                IsGraduated  = true,
                Age = 25
            },
            new Person{
                FirstName = "Hung",
                LastName = "Ngo Quoc",
                Gender = "Male",
                DateOfBirth = new DateTime(1991,3,7),
                PhoneNumber="",
                BirthPlace = "Hai Phong",
                IsGraduated  = false,
                Age = 30
            },
            new Person{
                FirstName = "Van",
                LastName = "Nguyen Cong",
                Gender = "Male",
                DateOfBirth = new DateTime(1998,4,5),
                PhoneNumber="",
                BirthPlace = "Ha Noi",
                IsGraduated  = true,
                Age = 23
            },
            new Person{
                FirstName = "Trang",
                LastName = "Nguyen Huyen",
                Gender = "Female",
                DateOfBirth = new DateTime(2002,7,14),
                PhoneNumber="",
                BirthPlace = "Hai Duong",
                IsGraduated  = false,
                Age = 19
            },
            new Person{
                FirstName = "Ky",
                LastName = "Nguyen Khac",
                Gender = "Male",
                DateOfBirth = new DateTime(1999,11,12),
                PhoneNumber="",
                BirthPlace = "Ha Noi",
                IsGraduated  = false,
                Age = 22
            },
            new Person{
                FirstName = "Phuoc",
                LastName = "Hoang",
                Gender = "Male",
                DateOfBirth = new DateTime(2000,11,25),
                PhoneNumber="",
                BirthPlace = "Hai Phong",
                IsGraduated  = false,
                Age = 21
            },
            new Person{
                FirstName = "Hung",
                LastName = "Bui",
                Gender = "Male",
                DateOfBirth = new DateTime(1983,11,13),
                PhoneNumber="",
                BirthPlace = "Ha Noi",
                IsGraduated  = true,
                Age = 38
            }
        };

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            HttpContext.Session.SetString("SESSION_USER", "Tuan Dat");
            return View();
        }

        public IActionResult Privacy()
        {
            var user = HttpContext.Session.GetString("SESSION_USER");
            return View("Privacy", user);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RookiesController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Text.Json;
using SessionDI.Models;
using Microsoft.AspNetCore.Http;

namespace SessionDI.Controllers
{
    public class RookiesController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IPersonServices _person;

        public RookiesController(ILogger<HomeController> logger, IPersonServices person)
        {
            _logger = logger;
            _person = person;
        }
        public IActionResult Index()
        {
            var person = _person.GetAll();
            return View(person);
        }

        public IActionResult Detail(int id)
        {
            var model = _person.GetOne(id);
            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Person person)
        {
            //Kiem tra 2 lop, tang tinh an toan, bao mat
            if (!ModelState.IsValid)
            {
                ViewBag.Error = "Invalid Model!";
                return View();
            }
            _person.Create(person);
            return RedirectToAction("Index", _person);
        }

        public IActionResult Edit(Person person)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Error = JsonSerializer.Serialize(person);
                return View();
            }
            _person.Update(person);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var personTemp = _person.GetOne(id);
            return View(personTemp);
        }

        public IActionResult Result()
        {
            return View();
        }

        public IActionResult Delete(int id)
        {
            var personTemp = _person.GetOne(id);
            if (personTemp == null)
            {
                return BadRequest();
            }
            // save info of person to session on brower. after, delete action is running
            HttpContext.Session.SetString("DELETE_NAME_TEMP", personTemp.FullNames);
            _person.Delete(id);
            return RedirectToAction("Result");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">Building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Rookies/Create.cshtml
@model Person
@{
    ViewData["Title"] = "Create New Person";
}
<div>
<a href="@Url.ActionLink("Index", "Rookies")" class="btn btn-info mr-5"><i class="fa fa-arrow-left mr-2" aria-hidden="true"></i>Back</a>
<h3 class="d-inline-block mb-0">@ViewData["Title"]</h3>
</div>
    <hr />
        <div>@ViewBag.Data</div>
<div class="row">
    <div class="col-6 offset-3">
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName)
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName)
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender)
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth)
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber)
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email)
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthPlace)
                @Html.EditorFor(model => model.BirthPlace, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthPlace, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>

    </div>
}
</div>
</div>

Views/Rookies/Detail.cshtml
@model Person
@{
    ViewData["Title"] = "Person Detail";
}
<div>
    <a href="@Url.ActionLink("Index", "Rookies")" class="btn btn-info mr-5"><i class="fa fa-arrow-left mr-2"
            aria-hidden="true"></i>Back</a>
    <h3 class="d-inline-block mb-0">@ViewData["Title"]</h3>
</div>
<hr />
<div>@ViewBag.Data</div>
<div class="form-horizontal row">
    <div class="form-group col-6">
        @Html.LabelFor(model => model.FirstName)
        @*@Html.ValueFor: get value for label. label have input type is disable*@
        <label class="form-control">@Html.ValueFor(model => model.FirstName)</label>
    </div>

    <div class="form-group col-6">
        @Html.LabelFor(model => model.LastName)
        <label class="form-control">@Html.ValueFor(model => model.LastName)</label>
    </div>

    <div class="form-group col-6">
        @Html.LabelFor(model => model.Gender)
        <label class="form-control">@Html.ValueFor(model => model.Gender)</label>
    </div>

    <div class="form-group col-6">
        @Html.LabelFor(model => model.DateOfBirth)
        <label class="form-control">@Html.ValueFor(model => model.DateOfBirth)</label>
    </div>

    <div class="form-group col-6">
        @Html.LabelFor(model => model.PhoneNumber)
        <label class="form-control">@Html.ValueFor(model => model.PhoneNumber)</label>
    </div>

    <div class="form-group col-6">
        @Html.LabelFor(model => model.Email)
        <label class="form-control">@Html.ValueFor(model => model.Email)</label>
    </div>

    <div class="form-group col-6">
        @Html.LabelFor(model => model.BirthPlace)
        <label class="form-control">@Html.ValueFor(model => model.BirthPlace)</label>
    </div>

    <div class="form-group col-6">
    <a href="@Url.ActionLink("Delete", "Rookies", new {id = Model.Id})" class="btn btn-danger btn-sm"
              role="button"><i class="fa fa-trash-o mr-2" aria-hidden="true"></i>Delete</a>
    </div>

    @* <div class="form-group">
        <div class="col-md-offset-2 col-md-6">
        <input type="submit" value="Save" class="btn btn-success" />
        </div>
        </div> *@

</div>

Views/Rookies/Edit.cshtml
@model Person
@{
    ViewData["Title"] = "Edit Person";
}
<div>
<a href="@Url.ActionLink("Index", "Rookies")" class="btn btn-info mr-5"><i class="fa fa-arrow-left mr-2" aria-hidden="true"></i>Back</a>
<h3 class="d-inline-block mb-0">@ViewData["Title"]</h3>
</div>
    <hr />
        <div>@ViewBag.Data</div>
<div class="row">
    <div class="col-6 offset-3">
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName)
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName)
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender)
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth)
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber)
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email)
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthPlace)
                @Html.EditorFor(model => model.BirthPlace, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthPlace, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-6">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>

    </div>
}
</div>
</div>

Views/Rookies/Index.cshtml
@model List<Person>

@{
  ViewData["Title"] = "Rookies";
}

<div class="text-left">
  <h3 class="d-inline-block">Rookies</h3>
  <a href="@Url.ActionLink("Create", "Rookies")" class="btn btn-primary float-right"><i class="fa fa-plus-square-o mr-2"
      aria-hidden="true"></i>Creat New Person</a>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Id</th>
        <th scope="col">FullName</th>
        <th scope="col">Gender</th>
        <th scope="col">BirthDay</th>
        <th scope="col">Age</th>
        <th class="text-center">Actions</th>
      </tr>
    </thead>
    <tbody>
      @{
        int @index = 1;
        foreach (var item in Model)
        {
          <tr>
            <th scope="row">@(index++)</th>
            <td>@item.Id</td>
            <td>
              <a href="@Url.ActionLink("Detail", "Rookies", new {id = item.Id})" style="color:red;">@item.FullNames</a>
            </td>
            <td>@item.Gender</td>
            <td>@item.DateOfBirth.ToString("dd/MM/yyyy")</td>
            <td>@item.Age</td>
            <td class="text-center" width=200px>
              <a href="@Url.ActionLink("Edit", "Rookies", new {id = item.Id})" class="btn btn-secondary btn-sm"
              role="button"><i class="fa fa-pencil mr-2" aria-hidden="true"></i>Edit</a>
              <a onclick="Delete(@item.Id)" href="#" class="btn btn-danger btn-sm" role="button"><i
                class="fa fa-trash-o mr-2" aria-hidden="true"></i>Delete</a>
            </td>
          </tr>
        }
      }
    </tbody>
  </table>
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item">
        <a class="page-link" href="#" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      <li class="page-item"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      <li class="page-item"><a class="page-link" href="#">3</a></li>
      <li class="page-item">
        <a class="page-link" href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    </ul>
  </nav>
</div>
<script>
  function Delete(Id) {
    if (confirm("Are you sure you want to delete?"))
      location.href = `/Rookies/Delete?Id= + ${Id}`;
  }
</script>

Views/Rookies/Result.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor;
@{
    ViewData["Title"] = "Result Page";
    var name = HttpContextAccessor.HttpContext.Session.GetString("DELETE_NAME_TEMP");
}
<div>
    <a href="@Url.ActionLink("Index", "Rookies")" class="btn btn-info mr-5"><i class="fa fa-arrow-left mr-2"
            aria-hidden="true"></i>Back</a>
    <h3 class="d-inline-block mb-0">@ViewData["Title"]</h3>
</div>
<hr />
<h3 style="color: green;">Person @name was removed from the list successfully!</h3>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - C__ASP_.Net_Core_MVC_2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">C__ASP_.Net_Core_MVC_2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - C__ASP_.Net_Core_MVC_2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>